name: neodocs_package
description: A new Flutter package.
version: 1.0.1
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"

  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  rxdart: ^0.27.0
  web_socket_channel: ^3.0.0

  camera: ^0.11.0+1
  connectivity_plus: ^6.0.3
  device_info_plus: ^8.2.2
  wakelock: ^0.6.1+2
  uuid: ^4.4.0

  auto_size_text: ^3.0.0
  bot_toast: ^4.0.1
  simple_timer: ^2.0.0

  lottie: ^3.1.2
  timelines: ^0.1.0

  google_mlkit_barcode_scanning: ^0.12.0

  path_provider: ^2.0.9

  youtube_player_flutter: ^9.0.0
  flutter_screenutil: ^5.9.0

  flutter_svg: ^2.0.10+1
  pdf: ^3.10.8
  intl: ^0.19.0
  printing: ^5.12.0

  open_filex: ^4.4.0
  flutter_staggered_grid_view: ^0.7.0

# dependency_overrides:
#   camera_android: 0.9.7+1
#   camera_avfoundation: 0.9.7+1
dependency_overrides:
  #intl: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  assets:
    - assets/images/
    - assets/lottie/
    - assets/manrope/
    - assets/icon/
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: manrope
      fonts: 
        - asset: assets/manrope/Manrope-ExtraLight.ttf
          weight: 200
        - asset: assets/manrope/Manrope-Light.ttf
          weight: 300
        - asset: assets/manrope/Manrope-Regular.ttf
          weight: 400
        - asset: assets/manrope/Manrope-Medium.ttf
          weight: 500
        - asset: assets/manrope/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/manrope/Manrope-Bold.ttf
          weight: 700
        - asset: assets/manrope/Manrope-ExtraBold.ttf
          weight: 800
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
