name: web_sdk
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.15.1

  wasm_interop: ^2.0.1
  js: ^0.6.7

  http: ^1.1.0
  rxdart: ^0.27.0
  web_socket_channel: ^2.2.0

  #camera: 0.10.3+2
  connectivity_plus: ^2.2.1
  device_info_plus: ^3.2.1
  wakelock: ^0.6.1+2
  uuid: ^3.0.6

  auto_size_text: ^3.0.0
  bot_toast: ^4.0.1
  simple_timer: ^2.0.0

  lottie: ^1.2.2
  timelines: ^0.1.0

  r_scan: ^0.1.6+1
  path_provider: ^2.0.9

  youtube_player_iframe: ^4.0.4
  flutter_screenutil: ^5.6.0

  flutter_svg: ^1.1.6
  pdf: ^3.10.4
  intl: ^0.17.0
  printing: ^5.9.3

  open_filex: ^3.4.0
  flutter_staggered_grid_view: ^0.6.2

  image: ^4.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
    - assets/manrope/
    - assets/icon/
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: manrope
      fonts:
        - asset: assets/manrope/Manrope-ExtraLight.ttf
          weight: 200
        - asset: assets/manrope/Manrope-Light.ttf
          weight: 300
        - asset: assets/manrope/Manrope-Regular.ttf
          weight: 400
        - asset: assets/manrope/Manrope-Medium.ttf
          weight: 500
        - asset: assets/manrope/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/manrope/Manrope-Bold.ttf
          weight: 700
        - asset: assets/manrope/Manrope-ExtraBold.ttf
          weight: 800
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
